### ISSUE TITLE
[Feature-Request] Integration with GitHub Updater

### ISSUE THREAD

**Issue by afragen** [MyWorkAus/WP-Remote-WordPress-Plugin#158]
I have a project, GitHub Updater, https://github.com/afragen/github-updater

It hooks into the standard WP update mechanism to display updates for plugins and themes that are hosted on GitHub (or Bitbucket). I'd like to be able to integrate with WP Remote but at present updates that are available aren't showing up.

Integration with iThemes Sync and ManageWP is functioning and I'd like to make it work with all remote update services.

Thanks for any insight.

**Comment by JeramyNS** [comment]
Hey, 

This is something we can definitely look into for version 3.

I'll add it to our list of feature requests and let you know if I have any questions.

Cheers
