### ISSUE TITLE
URL and country code

### ISSUE THREAD

**Issue by marcelaerts** [MyWorkAus/WP-Remote-WordPress-Plugin#159]
We installed Wpremote but for some reason we can't connect to it from the adminpanel. We get the following message:

This site does not have the WP Remote WordPress Plugin installed.

When I look at the settings it shows an URL with a country code coming from the plugin WPML (/en/). The country code was added automatically in the Wpremote adminpanel settings. I think this is causing the problem. Is this a known bug and can it be fixed?

**Comment by JeramyNS** [comment]
Hey,

I apologize for the large delay in responding to your support request.
Due to the age of this support request I am now closing this issue.

If you are still having an issue, please let me know and I can re-open an investigation for you.

Kind Regards,

Jeramy Simpson
