### ISSUE TITLE
Update deprecated "mysql_" in secondary backup function

### ISSUE THREAD

**Issue by karenbennett** [MyWorkAus/WP-Remote-WordPress-Plugin#161]
I've been using the WP Remote plugin on many sites for several years. Yesterday I used the WP Engine PHP Compatibility Checker plugin (https://wordpress.org/plugins/php-compatibility-checker/) to check a site for a PHP upgrade. It listed warnings for wprp.hm.backup.php:

FILE: /home/hstki3/public_html/wp/wp-content/plugins/wpremote/wprp.hm.backup.php

FOUND 0 ERRORS AND 18 WARNINGS AFFECTING 18 LINES

  991 | WARNING | Extension 'mysql_' is deprecated since PHP 5.5 - use mysqli instead.
  994 | WARNING | Extension 'mysql_' is deprecated since PHP 5.5 - use mysqli instead.
  999 | WARNING | Extension 'mysql_' is deprecated since PHP 5.5 - use mysqli instead.
 1002 | WARNING | Extension 'mysql_' is deprecated since PHP 5.5 - use mysqli instead.
 1005 | WARNING | Extension 'mysql_' is deprecated since PHP 5.5 - use mysqli instead.
 1014 | WARNING | Extension 'mysql_' is deprecated since PHP 5.5 - use mysqli instead.
 1016 | WARNING | Extension 'mysql_' is deprecated since PHP 5.5 - use mysqli instead.
 1947 | WARNING | Extension 'mysql_' is deprecated since PHP 5.5 - use mysqli instead.
 1951 | WARNING | Extension 'mysql_' is deprecated since PHP 5.5 - use mysqli instead.
 1952 | WARNING | Extension 'mysql_' is deprecated since PHP 5.5 - use mysqli instead.
 1956 | WARNING | Extension 'mysql_' is deprecated since PHP 5.5 - use mysqli instead.
 1965 | WARNING | Extension 'mysql_' is deprecated since PHP 5.5 - use mysqli instead.
 1968 | WARNING | Extension 'mysql_' is deprecated since PHP 5.5 - use mysqli instead.
 1969 | WARNING | Extension 'mysql_' is deprecated since PHP 5.5 - use mysqli instead.
 1982 | WARNING | Extension 'mysql_' is deprecated since PHP 5.5 - use mysqli instead.
 1983 | WARNING | Extension 'mysql_' is deprecated since PHP 5.5 - use mysqli instead.
 2000 | WARNING | Extension 'mysql_' is deprecated since PHP 5.5 - use mysqli instead.
 2041 | WARNING | Extension 'mysql_' is deprecated since PHP 5.5 - use mysqli instead.

**Comment by JeramyNS** [comment]
The backup function that uses this deprecated feature is only executed when mysqldump is unavailable.

That means most server setups won't have a problem, however there is obviously some more restrictive environments running PHP7 that will have an issue. 

I will add this to a list of things to update.

Thanks 😄

**Comment by bmett** [comment]
fixed in version 2.7.8
