### ISSUE TITLE
Self Hosting 

### ISSUE THREAD

**Issue by kordianbruck** [MyWorkAus/WP-Remote-WordPress-Plugin#168]
I would love to see the ability to self host the WP-Remote Website itself. I'd like to set it up inside our VPN system and not have it communicate with other server.

**Comment by JeramyNS** [comment]
Unfortunately we don't expect to offer this sort of licensing option in the near future.

We would be open to anyone willing to make us an offer for such a license, however due to the complexity of the project such a venture wouldn't be cheap.
