### ISSUE TITLE
Minimum PHP version

### ISSUE THREAD

**Issue by mindctrl** [MyWorkAus/WP-Remote-WordPress-Plugin#172]
What's the minimum version required? I don't see it stated anywhere. 

Looking at the changelog history before you took the plugin over, I see a mention of PHP 5.2.x support. On August 25, 2017 you added `Bug fix for php 5.4 and lower`. With that I'm assuming you want it to work on versions prior to 5.4.

However, your latest commit [here](https://github.com/MyWorkAus/WP-Remote-WordPress-Plugin/commit/2705e877a7c1e9cfbeb1c91cb0d1d3bede73b8fa?w=1) uses the short array syntax, which was introduced in PHP 5.4. This will break on versions prior to that, if you still care about it.

**Comment by JeramyNS** [comment]
At this stage we have decided to support all versions of PHP that WordPress supports (5.2.4+).

When I originally added the code I was under the impression that WordPress only supported 5.4+, must have had the number around the wrong way in my head. 
I have now removed the short array syntax to keep compatibility with PHP 5.2.4+.

Thank you for noticing this issue :smile:
