### ISSUE TITLE
Work from issues?

### ISSUE THREAD

**Issue by mindctrl** [MyWorkAus/WP-Remote-WordPress-Plugin#173]
Question: Would it be possible for you to work from issues and pull requests? For people watching this repo, notifications don't happen for direct commits to `master`.

And it would be nice to maintain a history of issues and enhancements and be able to reference code to detailed bug/enhancement reports.

**Comment by JeramyNS** [comment]
Yeah, most of our GitHub issues are tracked in another private repo.
I'll try and keep WP Remote relevant issues in here from now on.
