### ISSUE TITLE
Certain hosting environments reject new 'safe update'

### ISSUE THREAD

**Issue by JeramyNS** [MyWorkAus/WP-Remote-WordPress-Plugin#179]
This issue is just to track the progress on determining the cause behind why certain hosts are rejecting the new update method.

The new post request is sent using Guzzle, rather than the WordPress function wp_remote_post().
Even if the POST request is identical, something is causing the Guzzle request to fail.

There appears to be two different problems happening here.
 - In one scenario it returns a 401 or a 403 Unauthorised. Which probably means a firewall is interfering with the request.
 - In the other scenario, it appears that the POST request isn't getting passed through at all, as the website returns the actual website instead of triggering the API logic.

For the moment, to mitigate the issue, the old update method will be used once the plugin update fails.

To be able to determine the cause of this problem, I am going to need access to one of these sites; which is something I am yet to acquire.

**Comment by n2rga** [comment]
Excellent
Thank you
I did the update and it stayed on https://app.maek.it/remote#/.....

I have a dedicated server so if you need me to test something for you let me know.
I can give you a test account also.

**Comment by JeramyNS** [comment]
Looks like everything has been working pretty well since our latest update to WP Remote (not the plugin).
Closing this issue but will re-open if anything comes up.
